"""Add superpower to Hero

Revision ID: 18f703260464
Revises: cffdb4172be0
Create Date: 2025-03-30 17:56:09.766364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f703260464'
down_revision = 'cffdb4172be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_index('ix_cities_name')
        batch_op.create_index(batch_op.f('ix_cities_name'), ['name'], unique=False)

    with op.batch_alter_table('heroes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('superpower', sa.String(), nullable=True))
        batch_op.drop_index('ix_heroes_name')
        batch_op.create_index(batch_op.f('ix_heroes_super_name'), ['super_name'], unique=False)

    with op.batch_alter_table('powers', schema=None) as batch_op:
        batch_op.drop_index('ix_powers_name')
        batch_op.create_index(batch_op.f('ix_powers_name'), ['name'], unique=False)

    with op.batch_alter_table('superheroes', schema=None) as batch_op:
        batch_op.drop_index('ix_superheroes_name')
        batch_op.create_index(batch_op.f('ix_superheroes_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('superheroes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_superheroes_name'))
        batch_op.create_index('ix_superheroes_name', ['name'], unique=False)

    with op.batch_alter_table('powers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_powers_name'))
        batch_op.create_index('ix_powers_name', ['name'], unique=False)

    with op.batch_alter_table('heroes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_heroes_super_name'))
        batch_op.create_index('ix_heroes_name', ['name'], unique=False)
        batch_op.drop_column('superpower')

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cities_name'))
        batch_op.create_index('ix_cities_name', ['name'], unique=False)

    # ### end Alembic commands ###
