"""Initial migration

Revision ID: 394f134fb538
Revises: 87f5fd8138a2
Create Date: 2025-03-30 18:50:39.169505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394f134fb538'
down_revision = '87f5fd8138a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_index('ix_cities_name')
        batch_op.create_index(batch_op.f('ix_cities_name'), ['name'], unique=False)

    with op.batch_alter_table('heroes', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('super_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('superpower',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_index('ix_heroes_super_name')

    with op.batch_alter_table('powers', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_index('ix_powers_name')

    with op.batch_alter_table('superheroes', schema=None) as batch_op:
        batch_op.drop_index('ix_superheroes_name')
        batch_op.create_index(batch_op.f('ix_superheroes_name'), ['name'], unique=False)
        batch_op.drop_column('power')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('superheroes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('power', sa.VARCHAR(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_superheroes_name'))
        batch_op.create_index('ix_superheroes_name', ['name'], unique=False)

    with op.batch_alter_table('powers', schema=None) as batch_op:
        batch_op.create_index('ix_powers_name', ['name'], unique=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('heroes', schema=None) as batch_op:
        batch_op.create_index('ix_heroes_super_name', ['super_name'], unique=False)
        batch_op.alter_column('superpower',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('super_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cities_name'))
        batch_op.create_index('ix_cities_name', ['name'], unique=False)

    # ### end Alembic commands ###
