"""Add superhero_id to heroes

Revision ID: 87f5fd8138a2
Revises: 18f703260464
Create Date: 2025-03-30 18:02:18.233631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87f5fd8138a2'
down_revision = '18f703260464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_index('ix_cities_name')
        batch_op.create_index(batch_op.f('ix_cities_name'), ['name'], unique=False)

    with op.batch_alter_table('heroes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('superhero_id', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_heroes_super_name')
        batch_op.create_index(batch_op.f('ix_heroes_super_name'), ['super_name'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_heroes_superhero_id_superheroes'), 'superheroes', ['superhero_id'], ['id'])

    with op.batch_alter_table('powers', schema=None) as batch_op:
        batch_op.drop_index('ix_powers_name')
        batch_op.create_index(batch_op.f('ix_powers_name'), ['name'], unique=False)

    with op.batch_alter_table('superheroes', schema=None) as batch_op:
        batch_op.drop_index('ix_superheroes_name')
        batch_op.create_index(batch_op.f('ix_superheroes_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('superheroes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_superheroes_name'))
        batch_op.create_index('ix_superheroes_name', ['name'], unique=False)

    with op.batch_alter_table('powers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_powers_name'))
        batch_op.create_index('ix_powers_name', ['name'], unique=False)

    with op.batch_alter_table('heroes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_heroes_superhero_id_superheroes'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_heroes_super_name'))
        batch_op.create_index('ix_heroes_super_name', ['super_name'], unique=False)
        batch_op.drop_column('superhero_id')

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cities_name'))
        batch_op.create_index('ix_cities_name', ['name'], unique=False)

    # ### end Alembic commands ###
