"""Initial migration

Revision ID: cffdb4172be0
Revises: 
Create Date: 2025-03-30 17:48:19.947431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cffdb4172be0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cities_name'), ['name'], unique=False)

    op.create_table('heroes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('super_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('heroes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_heroes_name'), ['name'], unique=False)

    op.create_table('powers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('powers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_powers_name'), ['name'], unique=False)

    op.create_table('hero_powers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strength', sa.String(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=True),
    sa.Column('power_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], name=op.f('fk_hero_powers_hero_id_heroes')),
    sa.ForeignKeyConstraint(['power_id'], ['powers.id'], name=op.f('fk_hero_powers_power_id_powers')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('superheroes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('power', sa.String(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_superheroes_city_id_cities')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('superheroes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_superheroes_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('superheroes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_superheroes_name'))

    op.drop_table('superheroes')
    op.drop_table('hero_powers')
    with op.batch_alter_table('powers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_powers_name'))

    op.drop_table('powers')
    with op.batch_alter_table('heroes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_heroes_name'))

    op.drop_table('heroes')
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cities_name'))

    op.drop_table('cities')
    # ### end Alembic commands ###
